// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB81bXRknlqLiEUcVnfB-kuNIbdmPRb_Zg',
    appId: '1:521897899852:web:7ebeb0bf6e7bbf805301e9',
    messagingSenderId: '521897899852',
    projectId: 'medireminderauthentication',
    authDomain: 'medireminderauthentication.firebaseapp.com',
    storageBucket: 'medireminderauthentication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKqRcCoaRIg3aQOBVdBkRmLWOq_ustUE',
    appId: '1:521897899852:android:f3d605a0cc915f725301e9',
    messagingSenderId: '521897899852',
    projectId: 'medireminderauthentication',
    storageBucket: 'medireminderauthentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjabEjTQRbymg3jDtlma6DPVls46TX9E',
    appId: '1:521897899852:ios:46f140ecfb1c73ae5301e9',
    messagingSenderId: '521897899852',
    projectId: 'medireminderauthentication',
    storageBucket: 'medireminderauthentication.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjabEjTQRbymg3jDtlma6DPVls46TX9E',
    appId: '1:521897899852:ios:956d8c37dfa074085301e9',
    messagingSenderId: '521897899852',
    projectId: 'medireminderauthentication',
    storageBucket: 'medireminderauthentication.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
